import type { Store } from "../server/db.ts";
import type { Api } from "../server/http.ts";

export const FAKE_TOKEN = "t".repeat(64);

/** `Api` de mentira para testar `createHandler` sem WhatsApp: tudo responde vazio; sobrescreva o que o teste observa. */
export function fakeApi(store: Store, over: Partial<Api> = {}): Api {
  return {
    store,
    distDir: "dist",
    port: 0,
    token: FAKE_TOKEN,
    state: () => ({}),
    send: async () => undefined,
    react: async () => undefined,
    editMessage: async () => undefined,
    forward: async () => undefined,
    watch: async () => undefined,
    typing: async () => undefined,
    sendMedia: async () => undefined,
    sendPoll: async () => undefined,
    businessQuickReplies: async () => [],
    vote: async () => null,
    sendLocation: async () => undefined,
    sendContacts: async () => undefined,
    sendSticker: async () => undefined,
    stickers: () => [],
    star: async () => ({ synced: true }),
    pin: async () => undefined,
    openChat: async () => null,
    setBlocked: async () => undefined,
    setEphemeral: async () => undefined,
    syncUnread: () => undefined,
    createGroup: async () => null,
    updateParticipants: async () => [],
    updateGroupInfo: async () => undefined,
    acceptInvite: async () => null,
    deleteMessage: async () => ({ synced: true }),
    participants: async () => [],
    profile: async () => ({}),
    photo: async () => null,
    markRead: async () => undefined,
    syncArchive: () => undefined,
    syncMute: () => undefined,
    syncPin: () => undefined,
    classify: async () => null,
    saveSettings: () => undefined,
    logout: async () => undefined,
    reset: async () => undefined,
    backup: async () => "",
    proposeVoucher: async (jid) => store.getChat(jid),
    agent: { list: () => [], start: (jid, step) => ({ jid, step }), dismiss: () => undefined },
    media: async () => ({ body: Buffer.from("0123456789"), mimetype: "audio/ogg", fileName: null }),
    transcribe: async () => "oi",
    cachedTranscript: async () => ({ text: null, summary: null }),
    summarizeAudio: async () => ({}),
    transcribeRecording: async () => "texto",
    mcp: { status: async () => ({ claudeFound: false, registered: false, command: null, file: "" }), register: async () => undefined, unregister: async () => undefined },
    ai: { status: () => ({}), draft: async () => "", summarize: async () => ({}), persona: async () => null, setInstructions: () => undefined, setProvider: () => undefined, setDeepseekModel: () => undefined, setClaudeModel: () => undefined, setSummaryModel: () => undefined, setDeepseekOptions: () => undefined, setClaudeOptions: () => undefined, setJevContext: () => undefined, usage: () => ({}), setUsdBrl: () => undefined },
    subscribe: (res) => res.end(),
    onChatChanged: () => undefined,
    ...over,
  };
}
